# Generated by Django 5.1.3 on 2024-11-07 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('icon', models.URLField(blank=True, null=True)),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('pubDate', models.DateTimeField()),
                ('pubDateTZ', models.CharField(max_length=50)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('language', models.CharField(max_length=50)),
                ('duplicate', models.BooleanField(default=False)),
                ('relevance_score', models.IntegerField()),
                ('relevance_reason', models.TextField()),
                ('categories', models.ManyToManyField(to='core.category')),
                ('countries', models.ManyToManyField(to='core.country')),
                ('keywords', models.ManyToManyField(to='core.keyword')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.source')),
            ],
            options={
                'verbose_name_plural': 'Stories',
            },
        ),
    ]
