# Generated by Django 5.1.3 on 2024-11-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_story_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemapurl',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
