# Generated by Django 5.1.3 on 2024-12-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remixable'),
    ]

    operations = [
        migrations.AddField(
            model_name='remixable',
            name='remixed_as',
            field=models.TextField(blank=True, null=True),
        ),
    ]
