# Generated by Django 5.1.3 on 2024-12-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remixableimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='remixable',
            name='remixed_image',
            field=models.FileField(blank=True, null=True, upload_to='remixed_images/'),
        ),
    ]
